#!/usr/bin/env bash
# Script that starts nginx as nginx user
chmod 777 /etc/nginx/nginx.confi
chown -R nginx /etc/nginx
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
pkill -9 apache
su -c "sudo systemctl restart nginx" nginx
